server:
  port: 8000
  servlet:
    context-path: /


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/project?serverTimezone=Asia/Seoul
    username: root
    password: tntor123
  batch:
    job:
      names: ${job.name:NONE} # ?? ??? arg ??? ???
      jdbc:
        initialize-schema: always
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false